"""Initial Migration

Revision ID: d2f0641348f4
Revises: 
Create Date: 2022-12-15 13:17:19.916911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f0641348f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profits', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pper', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargo', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('pper')
        batch_op.drop_column('profits')

    # ### end Alembic commands ###
